// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// PottsCompact_cpp
List PottsCompact_cpp(int kmin, double gamma, NumericVector nr, NumericVector res, NumericVector sq);
RcppExport SEXP _Battenberg_PottsCompact_cpp(SEXP kminSEXP, SEXP gammaSEXP, SEXP nrSEXP, SEXP resSEXP, SEXP sqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type kmin(kminSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res(resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sq(sqSEXP);
    rcpp_result_gen = Rcpp::wrap(PottsCompact_cpp(kmin, gamma, nr, res, sq));
    return rcpp_result_gen;
END_RCPP
}
// exactPcf_cpp
List exactPcf_cpp(NumericVector y, int kmin, double gamma);
RcppExport SEXP _Battenberg_exactPcf_cpp(SEXP ySEXP, SEXP kminSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type kmin(kminSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(exactPcf_cpp(y, kmin, gamma));
    return rcpp_result_gen;
END_RCPP
}
// findEst_cpp
List findEst_cpp(IntegerVector bestSplit, int N, NumericVector Nr, NumericVector Sum, bool yest);
RcppExport SEXP _Battenberg_findEst_cpp(SEXP bestSplitSEXP, SEXP NSEXP, SEXP NrSEXP, SEXP SumSEXP, SEXP yestSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type bestSplit(bestSplitSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Nr(NrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Sum(SumSEXP);
    Rcpp::traits::input_parameter< bool >::type yest(yestSEXP);
    rcpp_result_gen = Rcpp::wrap(findEst_cpp(bestSplit, N, Nr, Sum, yest));
    return rcpp_result_gen;
END_RCPP
}
// findMarks_cpp
LogicalVector findMarks_cpp(LogicalVector markSub, NumericVector Nr, int subsize);
RcppExport SEXP _Battenberg_findMarks_cpp(SEXP markSubSEXP, SEXP NrSEXP, SEXP subsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type markSub(markSubSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Nr(NrSEXP);
    Rcpp::traits::input_parameter< int >::type subsize(subsizeSEXP);
    rcpp_result_gen = Rcpp::wrap(findMarks_cpp(markSub, Nr, subsize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Battenberg_PottsCompact_cpp", (DL_FUNC) &_Battenberg_PottsCompact_cpp, 5},
    {"_Battenberg_exactPcf_cpp", (DL_FUNC) &_Battenberg_exactPcf_cpp, 3},
    {"_Battenberg_findEst_cpp", (DL_FUNC) &_Battenberg_findEst_cpp, 5},
    {"_Battenberg_findMarks_cpp", (DL_FUNC) &_Battenberg_findMarks_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_Battenberg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
