# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' PottsCompact C++ implementation
#' @param kmin Minimal length of plateau
#' @param gamma Penalty for discontinuity
#' @param nr number of values between breakpoints
#' @param res sum of values between breakpoints
#' @param sq sum of squares of values between breakpoints
#' @param yest boolean for estimation
#' @return List with bestCost and bestSplit
PottsCompact_cpp <- function(kmin, gamma, nr, res, sq) {
    .Call('_Battenberg_PottsCompact_cpp', PACKAGE = 'Battenberg', kmin, gamma, nr, res, sq)
}

#' exactPcf C++ implementation
#' @param y Input vector
#' @param kmin Minimal length of plateau
#' @param gamma Penalty
#' @return List with bestCost, bestAver, bestSplit
exactPcf_cpp <- function(y, kmin, gamma) {
    .Call('_Battenberg_exactPcf_cpp', PACKAGE = 'Battenberg', y, kmin, gamma)
}

#' findEst C++ implementation
#' @param bestSplit vector of best splits from DP
#' @param N number of compressed points
#' @param Nr number of original points in each compressed point
#' @param Sum sum of original values in each compressed point
#' @param yest boolean for estimation
#' @return List with segments and optionally yhat
findEst_cpp <- function(bestSplit, N, Nr, Sum, yest) {
    .Call('_Battenberg_findEst_cpp', PACKAGE = 'Battenberg', bestSplit, N, Nr, Sum, yest)
}

#' findMarks C++ implementation
#' @param markSub marks in compressed scale
#' @param Nr number of observations
#' @param subsize original scale size
#' @return LogicalVector of marks in original scale
findMarks_cpp <- function(markSub, Nr, subsize) {
    .Call('_Battenberg_findMarks_cpp', PACKAGE = 'Battenberg', markSub, Nr, subsize)
}

